name: For0For

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Enter your target!'
        required: false

jobs:
  For0For:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Assign target
      id: assign-target
      run: |
        if [ -z "${{ github.event.inputs.target_url }}" ]; then
          target_url=$(curl -s https://github.com/arkadiyt/bounty-targets-data/raw/refs/heads/main/data/wildcards.txt | shuf -n 1)
        else
          target_url="${{ github.event.inputs.target_url }}"
        fi
        echo "target_url=$target_url" >> $GITHUB_ENV

    - name: Fetch files from archive.org
      run: |
        wget -qO- "https://web.archive.org/cdx/search/cdx?url=${{ env.target_url }}/*&collapse=urlkey&output=text&fl=original&filter=original:.*\.(sql|db|backup|yml|yaml|ini|config|crt|pem|key|asc)$" | while read file; do echo 'https://web.archive.org/web/*/'$file >> files.txt; done

    - name: Count file exts
      run: |
        awk -F. '{print $NF}' files.txt | sort | uniq -c > ext-counts.txt

    - name: Notify Discord
      env:
        WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        file_count=$(cat files.txt | wc -l)
        if [ "$file_count" -gt 0 ]; then
          extension_counts=$(awk '{print $2 ": " $1}' ext-counts.txt | tr '\n' '\n')
          target_domain=$(echo "${{ env.target_url }}" | awk -F/ '{print $3}')
          curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"Found $file_count high-critic files of $target_domain! \n↓ Found exts ↓ \n$extension_counts\"}" $WEBHOOK_URL
