name: Sensitive Files Scanner

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Enter you target!'
        required: false
        type: string

jobs:
  For0For:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: setup
      run: |
        chmod +x ./For0For.sh
        sudo apt-get update
        sudo apt-get install -y curl jq
        
    - name: run
      id: scan
      run: |
        if [ -n "${{ github.event.inputs.target_url }}" ]; then
          output=$(./For0For.sh "${{ github.event.inputs.target_url }}")
        else
          output=$(./For0For.sh)
        fi
        echo "scan_output<<EOF" >> $GITHUB_ENV
        echo "$output" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: notify
      if: env.scan_output != ''
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        if [ -n "$DISCORD_WEBHOOK_URL" ]; then
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "${{ env.scan_output }}" \
               $DISCORD_WEBHOOK_URL
        else
          echo "Discord webhook URL not configured"
          exit 1
        fi
